src/migrator/urls.py
from django.urls import path, register_converter

from . import views

from .converters import LogfileConverter

register_converter(LogfileConverter, "log")

app_name = "migrator"

urlpatterns = [
    path("", views.index, name="index"),
    path("sync/", views.sync, name="sync"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks/<str:task_id>/", views.task_details, name="tasks-details"),
    path(
        "tasks/<str:task_id>/<log:filename>/",
        views.log_details,
        name="tasks-log-details",
    ),
    path(
        "tasks/<str:task_id>/<log:filename>/download/",
        views.download_log,
        name="tasks-log-download",
    ),
    path(
        "api/tasks/list/",
        views.CeleryTaskList.as_view(),
        name="api-tasks-list",
    ),
    path("api/tasks/retry/<str:task_id>", views.retry_task, name="api-retry-task"),
    path(
        "api/tasks/archive/",
        views.ArchiveTask.as_view(),
        name="api-tasks-archive",
    ),
    path(
        "api/tasks/cancel/",
        views.CancelTask.as_view(),
        name="api-tasks-cancel",
    ),
    path(
        "api/tasks/delete/",
        views.DeleteTask.as_view(),
        name="api-tasks-delete",
    ),
    path(
        "api/tasks/<str:task_id>/",
        views.CeleryTaskDetails.as_view(),
        name="api-tasks-details",
    ),
    path(
        "api/tasks/<str:task_id>/<log:log_file>/",
        views.CeleryTaskLogDetails.as_view(),
        name="api-tasks-log-details",
    ),
    path("account/", views.user_account, name="user-account"),
    path("update-account/", views.update_account, name="update-account"),
    path("update-preferences/", views.update_preferences, name="update-preferences"),
]

src/pymap/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.conf import settings

from migrator.admin import custom_admin_site

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # path("admin/", admin.site.urls),
    path("admin/", custom_admin_site.urls, name="index"),
    path("", include("migrator.urls", namespace="migrator")),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="admin/login.html",
            success_url="/sync",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
    path(
        "password-change/",
        login_required(auth_views.PasswordChangeView.as_view(success_url="/account")),
        name="password-change",
    ),
    path(
        "password-change-done/",
        login_required(auth_views.PasswordResetDoneView.as_view()),
        name="password-change-done",
    ),
] + ([path("__debug__/", include("debug_toolbar.urls"))] if settings.DEBUG else [])

src/migrator/forms.py
import json
import logging
import re
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from .models import UserPreferences

logger = logging.getLogger(__name__)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]


class JSONPrettyWidget(forms.Textarea):
    def format_value(self, value: str) -> str:
        # Pretty print the value before rendering
        try:
            value = json.loads(value)  # Ensure it's valid JSON
            return json.dumps(value, indent=4)
        except (TypeError, ValueError):
            return value  # If it's invalid, return as is


class PreferencesForm(forms.ModelForm):
    class Meta:
        model = UserPreferences
        fields = ["host_patterns"]

    def clean_host_patterns(self):
        patterns = self.data.get("host_patterns")
        try:
            if patterns:
                # Load the JSON string into a Python object (list)
                patterns_list = json.loads(patterns)

                # Clean each pattern by removing whitespace
                cleaned_patterns = [
                    [re.sub(r"\s+", "", pattern) for pattern in sublist]
                    for sublist in patterns_list
                ]

                # Return the cleaned list (not JSON string, just the Python object)
                return cleaned_patterns
        except (ValueError, TypeError):
            raise forms.ValidationError("Invalid JSON format")


class SyncForm(forms.Form):
    credentials_placeholder = "Source@Account Password Destination@Account Password\ntest@email.com Password123 test@email.com Password123"
    custom_label = forms.CharField(
        label="Custom Identifier(Optional)",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "..."}
        ),
        required=False,
        initial=""
    )
    source = forms.CharField(
        label="source",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "mail.source.tld"}
        ),
    )
    destination = forms.CharField(
        label="destination",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "sv.destination.tld"}
        ),
    )
    input_text = forms.CharField(
        label="input_text",
        widget=forms.Textarea(
            attrs={
                "class": "form-control w-75 mx-auto",
                "rows": 5,
                "autocomplete": "off",
                "placeholder": credentials_placeholder,
            }
        ),
    )
    additional_arguments = forms.CharField(
        label="additional_arguments",
        required=False,
        initial="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control d-inline-flex",
                "style": "max-width: 300px;",
                "placeholder": "--nossl1 --timeout 300 --office2  .....",
            }
        ),
    )
    dry_run = forms.BooleanField(
        label="dry_run",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input mx-2 mt-2"}),
    )

src/migrator/views.py
# mypy: disable-error-code="unused-ignore"
# Create your views here.
import logging
import re
import ast
from subprocess import PIPE, Popen, TimeoutExpired
from typing import List, Optional, Any
from os import listdir
from os.path import join
from pathlib import Path
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings
from django.urls import reverse
from django.utils.functional import SimpleLazyObject
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.http import (
    HttpResponse,
    JsonResponse,
    HttpResponseRedirect,
    HttpRequest,
    HttpResponseServerError,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Sum, Q

from rest_framework.views import APIView
from rest_framework.request import Request as APIRequest
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response as APIResponse
from rest_framework.exceptions import ValidationError
from rest_framework.generics import ListCreateAPIView

from .models import CeleryTask, UserPreferences
from .serializers import CeleryTaskSerializer, TaskIdListSerializer
from .forms import SyncForm, CustomUserChangeForm, PreferencesForm
from .tasks import call_system
from pymap import celery_app
from .utilites.helpers import get_logs_status
from core.pymap_core import ScriptGenerator

logger = logging.getLogger(__name__)


# IMPORTANT: All these views should be in the migrator: namespace


@login_required
def index(request: HttpRequest) -> HttpResponse:
    total_tasks = CeleryTask.objects.count()
    total_run_time = CeleryTask.objects.aggregate(Sum("run_time"))["run_time__sum"]
    total_n_accounts = CeleryTask.objects.aggregate(Sum("n_accounts"))[
        "n_accounts__sum"
    ]
    active_users_count = User.objects.filter(is_active=True).count()
    staff_count = User.objects.filter(is_active=True, is_staff=True).count()

    context = {
        "total_tasks": total_tasks,
        "total_run_time": total_run_time,
        "total_n_accounts": total_n_accounts,
        "active_users_count": active_users_count,
        "staff_count": staff_count,
    }
    return render(request, "home.html", context)


@login_required
def user_account(request: HttpRequest) -> HttpResponse:
    user = request.user
    preferences, _ = UserPreferences.objects.get_or_create(user=user)
    return render(request, "account.html", {"user": user, "preferences": preferences})


@login_required
def update_account(
    request: HttpRequest,
) -> (HttpResponse | HttpResponseRedirect):
    assert isinstance(request.user, User)  # AbstractBaseUser has no .username
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(
                "migrator:user-account", permanent=False
            )  # Redirect to user's account page after successful update
    else:
        form = CustomUserChangeForm(instance=request.user)
    username = request.user.username
    return render(request, "update_account.html", {"form": form, "username": username})


@login_required
def update_preferences(
    request: HttpRequest,
) -> (HttpResponse | HttpResponseRedirect):
    assert isinstance(request.user, User)  # AbstractBaseUser has no .username
    user_preferences, _ = UserPreferences.objects.get_or_create(user=request.user)
    if request.method == "POST":
        form = PreferencesForm(request.POST, instance=user_preferences)
        if form.is_valid():
            form.save()
            logger.debug(f"Updated user preferences for {request.user.username}")
            return redirect(
                "migrator:user-account", permanent=False
            )  # Redirect to user's account page after successful update
        else:
            logger.debug(f"Update preferences form is not valid: {form.errors}")
    else:
        form = PreferencesForm(instance=user_preferences)
    return render(request, "update_preferences.html", {"form": form})


@login_required
def tasks(request: HttpRequest) -> HttpResponse:
    """
    Renders task list template
    """
    return render(request, "tasks.html")


@login_required
@never_cache
def task_details(request: HttpRequest, task_id: str) -> HttpResponse:
    """
    Renders task list details from the provided task_id
    """
    task = get_object_or_404(CeleryTask, task_id=task_id)
    return render(
        request,
        "task_details.html",
        {
            "task_id": task_id,
            "task_finished": task.finished,
            "source": task.source,
            "destination": task.destination,
        },
    )


@login_required
def log_details(request: HttpRequest, task_id: str, filename: str) -> HttpResponse:
    """
    Renders individual log details template from task_id and filename
    """
    return render(
        request, "log_details.html", {"task_id": task_id, "filename": filename}
    )


@login_required
def sync(request: HttpRequest) -> (HttpResponse | HttpResponseRedirect):
    """
    Endpoint for requesting a sync, creates a new task and signals the worker
    """
    assert isinstance(request.user, User)  # AbstractBaseUser has no .username
    if request.method == "POST":
        form = SyncForm(request.POST)
        # logger.debug("POST data: %s", request.POST)
        if not form.is_valid():
            logger.error(f"Form errors: {form.errors}")
        else:
            # Process the form data, e.g., call Celery task
            # Access form.cleaned_data to get the input values
            # Example: form.cleaned_data['source'], form.cleaned_data['destination']
            # Call Celery task here with the input data
            source: str = form.cleaned_data["source"]
            destination: str = form.cleaned_data["destination"]
            # There area carriage returns being appended to the string probably due to the way
            # form parses and cleans data, make sure to remove them!!
            logger.debug("Input before split %s", form.cleaned_data["input_text"])
            clean_input = re.sub(r"\r\n", "\n", form.cleaned_data["input_text"].strip())
            input_text: List[str] = clean_input.split("\n")
            logger.debug("Input after split %s", input_text)
            additional_arguments: str = form.cleaned_data.get("additional_arguments", "")
            custom_label: str = form.cleaned_data.get("custom_label", "")
            dry_run: bool = form.cleaned_data["dry_run"]
            config = settings.PYMAP_SETTINGS
            user = request.user
            user_preferences, _ = UserPreferences.objects.get_or_create(user=user)
            additional_known_hosts = user_preferences.host_patterns
            logger.info(
                f"USER: {user.username} requested a sync for {source} -> {destination}"
            )
            logger.debug(
                f"""Source: {source}
                Destination: {destination}
                Additional arguments: {additional_arguments}
                Dry run: {dry_run}
                """
            )
            # TODO: Strip out passwords before logging commands
            # logger.debug(
            #     "Received the following input from client:\n %s", input_text
            # )
            gen = ScriptGenerator(
                source,
                destination,
                extra_args=additional_arguments,
                config=config,
                dry_run=dry_run,
                pymap_logdir=settings.PYMAP_LOGDIR,
                additional_known_hosts=additional_known_hosts,
            )
            content = gen.process_strings(input_text)

            # TODO: Strip out passwords before logging commands
            # logger.debug(
            #     "Received the following output from generator:\n %s", content
            # )

            task = call_system.apply_async((content,), countdown=5)  # type: ignore
            logger.info(
                f"Starting background task with ID: {task.id} from User: {user.username}"
            )

            # Don't forget to save the task id and respective inputs to the database
            root_log_directory: str = settings.PYMAP_LOGDIR
            log_directory = Path(root_log_directory, task.id)
            if not log_directory.exists():
                log_directory.mkdir()
            domains = ", ".join(gen.domains)
            ctask = CeleryTask(
                task_id=task.id,
                source=source,
                destination=destination,
                log_path=str(log_directory),
                n_accounts=len(content),
                domains=domains,
                custom_label=custom_label,
                owner=user,
            )
            ctask.save()

            target_url = reverse("migrator:tasks-details", args=(task.id,))
            logger.debug("Target redirect: %s", target_url)
            return redirect(target_url, permanent=False)
    else:
        form = SyncForm()

    return render(request, "sync.html", {"form": form})


@login_required
def retry_task(
    request: HttpRequest, task_id: str
) -> (HttpResponse | HttpResponseRedirect):
    # This is to avoid -> Caution: A complex expression can overflow the C stack and cause a crash.
    MAX_LENGTH = 20000

    def validate_and_evaluate(input_str: str, max_length=MAX_LENGTH) -> Any:
        if len(input_str) > max_length:
            raise ValueError(
                f"Input string exceeds the maximum length of {max_length} characters."
            )
        return ast.literal_eval(input_str)

    assert isinstance(request.user, User)
    user = request.user
    source = None
    destination = None
    try:
        db_result = CeleryTask.objects.get(task_id=task_id)
        finished = db_result.finished
        if not finished:

src/migrator/templates/account.html
<!-- user_account.html -->

{% extends 'structure/base.html' %}
{% block title %}User Account{% endblock %}

{% block content %}
<div class="container-fluid mt-5" style="width: 90%;">
    <h2>User Account</h2>
    <hr>
    <div class="d-flex justify-content-evenly">
        <div class="card" style="width: 45%;">
            <div class="card-header text-center">
                <h5 class="card-title mb-0">User Information</h5>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Username:</strong> {{ user.username }}</li>
                    <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                    <li class="list-group-item"><strong>First name:</strong> {{ user.first_name }}</li>
                    <li class="list-group-item"><strong>Last name:</strong> {{ user.last_name }}</li>
                    <li class="list-group-item"><strong>Staff:</strong> {{ user.is_staff }}</li>
                    <li class="list-group-item"><strong>Last login:</strong> {{ user.last_login }}</li>
                    <li class="list-group-item"><strong>Creation Date:</strong> {{ user.date_joined }}</li>
                </ul>
            </div>
            <div class="card-footer">
                <a href="{% url 'password-change' %}" class="btn btn-primary">Change Password</a>
                <a href="{% url 'migrator:update-account' %}" class="btn btn-primary">Update Information</a>
            </div>
        </div>
        <div class="card" style="width: 45%;">
            <div class="card-header text-center">
                <h5 class="card-title mb-0">User Preferences</h5>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Replacement patterns:</strong> <pre>{{ preferences.host_patterns | pprint }}</pre></li>
                </ul>
            </div>
            <div class="card-footer">
                <a href="{% url 'migrator:update-preferences' %}" class="btn btn-primary">Update</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/migrator/templates/home.html
{% extends 'structure/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h1>Stats</h1>
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item text-center fs-5">Tasks</li>
                <li class="list-group-item">Total number of tasks: {{ total_tasks }}</li>
                <li class="list-group-item">Number of accounts synced across all tasks: {{ total_n_accounts }}</li>
                <li id="total_run_time" class="list-group-item">Sum of the run time of all tasks: {{ total_run_time }}</li>
                <hr>
            </ul>
        </div>
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item text-center fs-5">Pymap</li>
                <li class="list-group-item">Number of active users: {{ active_users_count }}</li>
            </ul>
        </div>
    </div>
</div>

<script>
    // https://stackoverflow.com/questions/36098913/convert-seconds-to-days-hours-minutes-and-seconds
    function secondsToDhms(seconds) {
        seconds = Number(seconds);
        var d = Math.floor(seconds / (3600*24));
        var h = Math.floor(seconds % (3600*24) / 3600);
        var m = Math.floor(seconds % 3600 / 60);
        var s = Math.floor(seconds % 60);
        
        var dDisplay = d > 0 ? d + (d == 1 ? " day, " : " days, ") : "";
        var hDisplay = h > 0 ? h + (h == 1 ? " hour, " : " hours, ") : "";
        var mDisplay = m > 0 ? m + (m == 1 ? " minute, " : " minutes, ") : "";
        var sDisplay = s > 0 ? s + (s == 1 ? " second" : " seconds") : "";
        return dDisplay + hDisplay + mDisplay + sDisplay;
    }
    
    $(document).ready(()=>{
        el = document.getElementById("total_run_time");
        el.innerHTML = "Sum of the run time of all tasks: " + secondsToDhms("{{ total_run_time }}")
    })
</script>
{% endblock %}

src/migrator/templates/log_details.html
{% extends 'structure/base.html' %}

{% block content %}
<div class="container">
    <div class="d-flex flex-column align-items-center mb-3">
        <h2 class="w-100 text-center mb-3">Task ID: {{ task_id }}</h2>
        <h4 class="w-100 text-center">
            Log file: 
            <a href="{% url 'migrator:tasks-log-download' task_id=task_id filename=filename %}">{{ filename }}</a>
        </h3>
    </div>
    <div class="d-flex justify-content-evenly mb-3">
        <input type="number" class="form-control w-25" id="tail-timeout" placeholder="Tail timeout" onchange="updateTailParams(this)"/>
        <input type="number" class="form-control w-25" id="tail-count" placeholder="Tail count" onchange="updateTailParams(this)"/>
        <button class="btn btn-secondary" id="refresh-button" onclick="refreshListener(this)">
            Follow
        </button>
        <button class="btn btn-link" onclick="fetchData()">
            Update
        </button>
    </div>
    <div class="d-flex justify-content-evenly">
        <textarea id="log-content" class="form-control" rows="4" style="width: 90%; margin-bottom: 1em; height: 50vh;" disabled>
        </textarea>
    </div>
</div>

<script>
    let intervalId = null; // Variable to store the interval ID
    let tCount = 100;
    let tTimeout = 5;

    const updateTailParams = (e) => {
        if(e.id == "tail-timeout") {
            tTimeout = e.value
        } else if (e.id == "tail-count") {
            tCount = e.value
        }
    }
    
    const refreshListener = async (e)=>{
        if (intervalId === null) {
            // Start executing
            await fetchData();
            intervalId = setInterval(fetchData, 5000);
            e.innerText = "Stop";
            e.classList.remove('btn-secondary');
            e.classList.add('btn-success');
        } else {
            // Stop execution if already running
            clearInterval(intervalId);
            intervalId = null;
            e.innerText = "Follow";
            e.classList.add('btn-secondary');
            e.classList.remove('btn-success');
        }
    }
    
    const fetchData = async () => {
        const textArea = document.getElementById('log-content');
        const APIURL = `/api/tasks/{{task_id}}/{{filename}}?tcount=${tCount}&ttimeout=${tTimeout}`;
        
        try {
            const response = await fetch(APIURL);
            
            if (!response.ok) {
                throw new Error(`HTTP error! Status: ${response.status}`);
            }
            
            const responseData = await response.json();
            
            if (responseData.content) {
                if (responseData.error) {
                    console.error(`Error: ${responseData.error}`);
                }
                textArea.value = responseData.content;
                textArea.scrollTop = textArea.scrollHeight;
            } else if (responseData.error) {
                alert("Error, check console")
                console.error(`API Error: ${responseData.error}, ${responseData.data}`);
            } else {
                alert("Unknown API error");
            }
        } catch (error) {
            console.error(`Fetch error: ${error.message}`);
            // Handle other errors as needed
        }
    };
    
    $(document).ready(async ()=>{
        await fetchData();
        document.getElementById('tail-timeout').value = tTimeout;
        document.getElementById('tail-count').value = tCount;
    })
    
</script>
{% endblock %}

src/migrator/templates/sync.html
{% extends 'structure/base.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{% url 'migrator:sync' %}">
        {% csrf_token %}
        <div class="row mb-2 fs-5">
            <div class="col-md-6 text-center">
                <label for="{{ form.source.id_for_label }}" class="form-label">Source:</label>
                {{form.source}}
            </div>
            
            <div class="col-md-6 text-center">
                <label for="{{ form.destination.id_for_label }}" class="form-label">Destination:</label>
                {{form.destination}}
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-md-12 text-center">
                <div class="w-25 m-auto">
                    <label for="{{ form.custom_label.id_for_label }}" class="form-label">Custom Identifier</label>
                    {{form.custom_label}}
                </div>
            </div>
        </div>
        
        <div class="row mb-5">
            <div class="col-12 text-center fs-5">
                <label for="{{ form.input_text.id_for_label }}" class="form-label">Input</label>
                {{form.input_text}}
            </div>
        </div>
        
        <div class="row mb-5 fs-5">
            <div class="col-md-6">
                <label for="{{ form.additional_arguments.id_for_label }}" class="form-label d-inline-flex">Additional Arguments:</label>
                {{form.additional_arguments}}
            </div>
            <div class="col-md-3">
                <label for="{{ form.dry_run.id_for_label }}" class="form-check-label">Dry Run</label>
                {{form.dry_run}}
            </div>
            <!-- <div class="col-md-3">
                <button class="btn btn-success">Validate</button>
            </div> -->
        </div>
        
        
        <div class="row mb-5">
            <div class="col-12 text-center">
                <button type="submit" class="btn btn-primary" value="submit">Start Sync</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/migrator/templates/task_details.html
{% extends 'structure/base.html' %}

{% block script %}
{% include 'structure/datatables.html' %}
{% endblock %}

{% block content %}

<style>
    .round-btn {
        cursor: pointer;
        color: blue;
        text-decoration: underline;
        display: inline;
        padding: 5px 8px;
        border-radius: 50px;
        margin-left: 10px;
    }
    .round-btn:hover {
        background-color: lightblue;
    }
    .round-btn.disabled {
        pointer-events: none; /* Prevents clicking */
        opacity: 0.5; /* Makes button look disabled */
        cursor: not-allowed; /* Changes cursor to indicate disabled state */
    }
</style>

<div class="container mt-3 pb-5">
    <div class="pb-3">
        <h2 id="task-id" class="w-50 d-inline">{{ task_id }}</h2>
        <i id="copy-btn" class="round-btn bi bi-clipboard"></i>
        <i id="restart-btn" class="round-btn bi bi-arrow-repeat {% if not task_finished %}disabled{% endif %}"></i>
    </div>
    <div>
        <h3>{{source}} -> {{destination}}</h3>
    </div>
    <table id="taskDetails" class="table">
        <thead>
            <tr>
                <th>Logfile</th>
                <th>Start time</th>
                <th>End Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <!-- Dynamic data goes here -->
        </tbody>
    </table>
</div>

<script>
    var taskDetails;
    
    // Datatable row onClick
    $(document).on('click','#taskDetails tr',function(e){
        var data = taskDetails.row(this).data();
        if (data) {
            var log_file = data['log_file'];
            var task_id = "{{ task_id }}"
            var travel = `/tasks/${task_id}/${log_file}`
            window.location.href = travel;
        }
    });
    
    document.addEventListener('DOMContentLoaded', (event) => {
        document.getElementById('copy-btn').addEventListener('click', function() {
            var taskId = $('#task-id').text();
            
            // Use the Clipboard API to copy text
            navigator.clipboard.writeText(taskId).then(function() {
                // Optionally, show a message or provide feedback to the user
                alert('Copied task ID: ' + taskId);
            }).catch(function(error) {
                console.error('Failed to copy text: ', error);
            });
        });
        document.getElementById('restart-btn').addEventListener('click', function() {
            var taskId = $('#task-id').text();
            var redirectUrl = "{% url 'migrator:api-retry-task' 'TASK_ID_PLACEHOLDER' %}".replace('TASK_ID_PLACEHOLDER', taskId);
            window.location.href = redirectUrl;  // This will redirect the user to the new URL
        });
    });
    
    $(document).ready(function () {
        // Function to initialize the DataTable with server-side processing
        const initializeDataTable = () => {
            taskDetails = $('#taskDetails').DataTable({
                serverSide: true,
                processing: true,
                searching: true,
                ordering: true,
                pageLength: 15,
                paging: true,
                search: {
                    return: true
                },
                order: [[3, 'asc']],
                ajax: {
                    url: '/api/tasks/'+'{{ task_id }}',
                    type: 'GET',
                },
                columns: [
                {data: 'log_file', width: '900px'},
                {data: 'start_time', width: '250px'},
                {data: 'end_time', width: '250px'},
                {data: 'status', width: '200px'},
                ]
            });
        };
        
        // Run the initializeDataTable function on document load
        initializeDataTable();
    });
</script>

{% endblock %}

src/migrator/templates/update_account.html
<!-- update_account.html -->

{% extends 'structure/base.html' %}
{% block title %}Update User Account{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Update Account Information</h2>
    <hr>
    <div class="d-flex">
        <div class="card w-50 m-auto">
            <div class="card-header">
                <h2 class="card-title">{{username}}</h2>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label">Email:</label>
                        {{ form.email }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name:</label>
                        {{ form.first_name }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name:</label>
                        {{ form.last_name }}
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}